addSbtPlugin("com.typesafe.sbt"      % "sbt-native-packager" % "1.7.5")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"        % "0.9.24")
addSbtPlugin("io.spray"              % "sbt-revolver"        % "0.9.1")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"          % "6.4.2")
