addSbtPlugin("com.eed3si9n"          % "sbt-assembly" % "0.15.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix" % "0.9.21")
addSbtPlugin("io.spray"              % "sbt-revolver" % "0.9.1")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"   % "6.4.2")
