addSbtPlugin("com.eed3si9n"          % "sbt-assembly" % "0.14.10")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt" % "2.3.2")
addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix" % "0.9.15")
addSbtPlugin("io.spray"              % "sbt-revolver" % "0.9.1")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"   % "6.4.2")
