# Initialize a session
# https://docs.openvidu.io/en/2.14.0/reference-docs/REST-API/#post-apisessions
POST https://localhost:4443/api/sessions HTTP/1.1
Authorization: Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU
content-type: application/json

{
    "customSessionId": "test-session"
}

# Respoinse
# {
#   "id": "test-session",
#   "createdAt": 1588768585016
# }


###

# https://docs.openvidu.io/en/2.14.0/reference-docs/REST-API/#get-apisessions
GET https://localhost:4443/api/sessions HTTP/1.1
Authorization: Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU

# {
#   "numberOfElements": 1,
#   "content": [
#     {
#       "sessionId": "test-session",
#       "createdAt": 1588779496083,
#       "mediaMode": "ROUTED",
#       "recordingMode": "MANUAL",
#       "defaultOutputMode": "COMPOSED",
#       "defaultRecordingLayout": "BEST_FIT",
#       "customSessionId": "test-session",
#       "connections": {
#         "numberOfElements": 0,
#         "content": []
#       },
#       "recording": false
#     }
#   ]
# }

###
DELETE https://localhost:4443/api/sessions/test-session HTTP/1.1
Authorization: Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU
