GET http://localhost:8855/rest/api/v1/sessions HTTP/1.1

# {
#   "sessions": [
#     {
#       "createdAt": 1589041743400,
#       "sessionId": "test-session"
#     }
#   ]
# }

###

POST http://localhost:8855/rest/api/v1/sessions HTTP/1.1
content-type: application/json

{
    "sessionId": "test-session"
}

# {
#   "session": {
#     "createdAt": 1589820164540,
#     "sessionId": "test-session"
#   }
# }
