POST http://localhost:8855/rest/api/v1/auth/signup HTTP/1.1
content-type: application/json

{
    "name": "abcd",
    "display_name": "shoma",
    "email": "shoma.test@test.com",
    "password": "password"
}

# {}